/**
 * Downloads the design-system typefaces into web/public/fonts and writes the
 * @font-face block that loads them.
 *
 * SELF-HOSTED, not linked. A font request to a third party on a financial app
 * leaks usage metadata (when the operator opens their books, and from where),
 * adds a render-blocking dependency on someone else's uptime, and forces the
 * CSP to widen for a host that has nothing to do with Ballast. The stacks in
 * tokens.css named these three faces from the start; nothing ever shipped
 * them, so every screen has been rendering in a fallback serif.
 *
 * Only the latin subset is fetched — this is a single-operator US tool.
 */

import { mkdirSync, writeFileSync } from 'node:fs';

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const OUT = 'web/public/fonts';
mkdirSync(OUT, { recursive: true });

const API =
  'https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@600;700' +
  '&family=Hanken+Grotesk:wght@400;500;600&family=Space+Mono:wght@400;700&display=swap';

const css = await (await fetch(API, { headers: { 'User-Agent': UA } })).text();

// Google emits one @font-face per family/weight/subset, each preceded by a
// `/* latin */` style comment naming the subset.
const blocks = css.split('/*').slice(1);
const faces = [];

for (const raw of blocks) {
  const subset = raw.slice(0, raw.indexOf('*/')).trim();
  if (subset !== 'latin') continue;

  const family = /font-family:\s*'([^']+)'/.exec(raw)?.[1];
  const weight = /font-weight:\s*(\d+)/.exec(raw)?.[1];
  const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(raw)?.[1];
  const range = /unicode-range:\s*([^;]+);/.exec(raw)?.[1];
  if (!family || !weight || !url) continue;

  const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}.woff2`;
  const bytes = Buffer.from(
    await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer(),
  );
  writeFileSync(`${OUT}/${file}`, bytes);
  faces.push({ family, weight, file, range, kb: bytes.length / 1024 });
  console.log(`  ${file}  ${(bytes.length / 1024).toFixed(1)} KB`);
}

const header = `/* Design-system typefaces — SELF-HOSTED, generated by scripts/fetch-fonts.mjs.
 *
 * Do not hand-edit; re-run the script instead.
 *
 * These are the three faces tokens.css has always named (--display, --body,
 * --data). Until this file existed none of them shipped, so every surface fell
 * back to a system serif and the app did not look like its own design system.
 *
 * font-display: swap — text paints immediately in the fallback and reflows when
 * the face lands. On a glanceable money surface, showing the figure late is
 * worse than showing it in the wrong face for 100ms.
 *
 * Latin subset only: single-operator US tool.
 */
`;

const body = faces
  .map(
    (f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${f.file}') format('woff2');${f.range ? `\n  unicode-range: ${f.range};` : ''}
}`,
  )
  .join('\n\n');

writeFileSync('web/src/styles/fonts.css', `${header}\n${body}\n`);
console.log(`\n${faces.length} faces, ${faces.reduce((n, f) => n + f.kb, 0).toFixed(1)} KB total`);
